version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mot-mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mot-trees-root
      MYSQL_DATABASE: mot_trees
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: mot-adminer
    restart: always
    ports:
      - 3307:8080

volumes:
  mysql-data:
